import React, { useState, useEffect } from 'react';
import { useForm } from 'react-hook-form';
import Button from '../../../components/ui/Button';
import Input from '../../../components/ui/Input';
import Select from '../../../components/ui/Select';
import { Checkbox } from '../../../components/ui/Checkbox';
import Icon from '../../../components/AppIcon';

const InvoiceConfigurationModal = ({ isOpen, onClose, onSave, currentConfig = {} }) => {
  const [activeTab, setActiveTab] = useState('elements');
  
  const {
    register,
    handleSubmit,
    formState: { errors },
    setValue,
    watch,
    reset
  } = useForm({
    defaultValues: {
      // Invoice Elements Configuration
      showStudentName: currentConfig?.invoiceElements?.studentName ?? true,
      showStudentId: currentConfig?.invoiceElements?.studentId ?? true,
      showStudentClass: currentConfig?.invoiceElements?.studentClass ?? true,
      showParentInfo: currentConfig?.invoiceElements?.parentInfo ?? true,
      showSchoolName: currentConfig?.invoiceElements?.schoolName ?? true,
      showSchoolAddress: currentConfig?.invoiceElements?.schoolAddress ?? true,
      showSchoolEmail: currentConfig?.invoiceElements?.schoolEmail ?? true,
      showSchoolPhone: currentConfig?.invoiceElements?.schoolPhone ?? true,
      showInvoiceNumber: currentConfig?.invoiceElements?.invoiceNumber ?? true,
      showIssueDate: currentConfig?.invoiceElements?.issueDate ?? true,
      showDueDate: currentConfig?.invoiceElements?.dueDate ?? true,
      showSessionTerm: currentConfig?.invoiceElements?.sessionTerm ?? true,
      showPaymentBreakdown: currentConfig?.invoiceElements?.paymentBreakdown ?? true,
      showQrCode: currentConfig?.invoiceElements?.qrCode ?? false,
      showWatermark: currentConfig?.invoiceElements?.watermark ?? false,
      showSkupadiBranding: currentConfig?.invoiceElements?.skupadiBranding ?? true,
      showPaymentInstructions: currentConfig?.invoiceElements?.paymentInstructions ?? true,
      showInstallmentOptions: currentConfig?.invoiceElements?.installmentOptions ?? false,

      // Layout & Styling
      invoiceColorScheme: currentConfig?.invoiceColorScheme || 'blue',
      invoiceTemplate: currentConfig?.invoiceTemplate || 'standard',
      logoPosition: currentConfig?.logoPosition || 'top-center',
      watermarkPosition: currentConfig?.watermarkPosition || 'center-middle',
      headerStyle: currentConfig?.headerStyle || 'standard',
      footerStyle: currentConfig?.footerStyle || 'standard',

      // Content Settings
      invoiceTitle: currentConfig?.invoiceTitle || 'SCHOOL FEE INVOICE',
      paymentInstructions: currentConfig?.paymentInstructions || 'Please make payment before the due date to avoid late fees.',
      footerMessage: currentConfig?.footerMessage || 'Thank you for choosing our school!',
      issuerName: currentConfig?.issuerName || 'Skupadi System',
      
      // Terms & Conditions
      showTermsConditions: currentConfig?.showTermsConditions ?? true,
      termsConditions: currentConfig?.termsConditions || 'Payment terms and conditions apply.',
      
      // Payment Information
      showBankDetails: currentConfig?.showBankDetails ?? true,
      showPaymentMethods: currentConfig?.showPaymentMethods ?? true,
      showOnlinePaymentLink: currentConfig?.showOnlinePaymentLink ?? false,
      
      // QR Code Settings
      qrCodeSize: currentConfig?.qrCodeSize || 'medium',
      qrCodePosition: currentConfig?.qrCodePosition || 'bottom-right',
      includeInvoiceId: currentConfig?.includeInvoiceId ?? true,
      includePaymentReference: currentConfig?.includePaymentReference ?? true,
      includeVerificationUrl: currentConfig?.includeVerificationUrl ?? false,

      // Advanced Options
      showItemQuantity: currentConfig?.showItemQuantity ?? true,
      showUnitPrices: currentConfig?.showUnitPrices ?? true,
      showSubtotal: currentConfig?.showSubtotal ?? true,
      showDiscounts: currentConfig?.showDiscounts ?? true,
      showTaxes: currentConfig?.showTaxes ?? false,
      showLateFees: currentConfig?.showLateFees ?? true,
      currencyFormat: currentConfig?.currencyFormat || 'NGN',
      dateFormat: currentConfig?.dateFormat || 'DD/MM/YYYY',
      
      // Signature Settings
      includeDigitalSignature: currentConfig?.includeDigitalSignature ?? true,
      signatureText: currentConfig?.signatureText || 'Digitally generated by Skupadi',
      showPoweredBy: currentConfig?.showPoweredBy ?? true,
      
      // Late Payment Settings
      showLateFeeWarning: currentConfig?.showLateFeeWarning ?? true,
      lateFeeWarningText: currentConfig?.lateFeeWarningText || 'Late payment fees may apply after due date.',
      
      // Contact Information
      showContactInfo: currentConfig?.showContactInfo ?? true,
      contactPersonName: currentConfig?.contactPersonName || '',
      contactPersonTitle: currentConfig?.contactPersonTitle || 'Bursar'
    }
  });

  const watchedValues = watch();

  // Update form when config changes
  useEffect(() => {
    if (currentConfig && Object.keys(currentConfig)?.length > 0) {
      reset({
        // Invoice Elements Configuration
        showStudentName: currentConfig?.invoiceElements?.studentName ?? true,
        showStudentId: currentConfig?.invoiceElements?.studentId ?? true,
        showStudentClass: currentConfig?.invoiceElements?.studentClass ?? true,
        showParentInfo: currentConfig?.invoiceElements?.parentInfo ?? true,
        showSchoolName: currentConfig?.invoiceElements?.schoolName ?? true,
        showSchoolAddress: currentConfig?.invoiceElements?.schoolAddress ?? true,
        showSchoolEmail: currentConfig?.invoiceElements?.schoolEmail ?? true,
        showSchoolPhone: currentConfig?.invoiceElements?.schoolPhone ?? true,
        showInvoiceNumber: currentConfig?.invoiceElements?.invoiceNumber ?? true,
        showIssueDate: currentConfig?.invoiceElements?.issueDate ?? true,
        showDueDate: currentConfig?.invoiceElements?.dueDate ?? true,
        showSessionTerm: currentConfig?.invoiceElements?.sessionTerm ?? true,
        showPaymentBreakdown: currentConfig?.invoiceElements?.paymentBreakdown ?? true,
        showQrCode: currentConfig?.invoiceElements?.qrCode ?? false,
        showWatermark: currentConfig?.invoiceElements?.watermark ?? false,
        showSkupadiBranding: currentConfig?.invoiceElements?.skupadiBranding ?? true,
        showPaymentInstructions: currentConfig?.invoiceElements?.paymentInstructions ?? true,
        showInstallmentOptions: currentConfig?.invoiceElements?.installmentOptions ?? false,

        // Layout & Styling
        invoiceColorScheme: currentConfig?.invoiceColorScheme || 'blue',
        invoiceTemplate: currentConfig?.invoiceTemplate || 'standard',
        logoPosition: currentConfig?.logoPosition || 'top-center',
        watermarkPosition: currentConfig?.watermarkPosition || 'center-middle',
        headerStyle: currentConfig?.headerStyle || 'standard',
        footerStyle: currentConfig?.footerStyle || 'standard',

        // Content Settings
        invoiceTitle: currentConfig?.invoiceTitle || 'SCHOOL FEE INVOICE',
        paymentInstructions: currentConfig?.paymentInstructions || 'Please make payment before the due date to avoid late fees.',
        footerMessage: currentConfig?.footerMessage || 'Thank you for choosing our school!',
        issuerName: currentConfig?.issuerName || 'Skupadi System',
        
        // Terms & Conditions
        showTermsConditions: currentConfig?.showTermsConditions ?? true,
        termsConditions: currentConfig?.termsConditions || 'Payment terms and conditions apply.',
        
        // Payment Information
        showBankDetails: currentConfig?.showBankDetails ?? true,
        showPaymentMethods: currentConfig?.showPaymentMethods ?? true,
        showOnlinePaymentLink: currentConfig?.showOnlinePaymentLink ?? false,
        
        // QR Code Settings
        qrCodeSize: currentConfig?.qrCodeSize || 'medium',
        qrCodePosition: currentConfig?.qrCodePosition || 'bottom-right',
        includeInvoiceId: currentConfig?.includeInvoiceId ?? true,
        includePaymentReference: currentConfig?.includePaymentReference ?? true,
        includeVerificationUrl: currentConfig?.includeVerificationUrl ?? false,

        // Advanced Options
        showItemQuantity: currentConfig?.showItemQuantity ?? true,
        showUnitPrices: currentConfig?.showUnitPrices ?? true,
        showSubtotal: currentConfig?.showSubtotal ?? true,
        showDiscounts: currentConfig?.showDiscounts ?? true,
        showTaxes: currentConfig?.showTaxes ?? false,
        showLateFees: currentConfig?.showLateFees ?? true,
        currencyFormat: currentConfig?.currencyFormat || 'NGN',
        dateFormat: currentConfig?.dateFormat || 'DD/MM/YYYY',
        
        // Signature Settings
        includeDigitalSignature: currentConfig?.includeDigitalSignature ?? true,
        signatureText: currentConfig?.signatureText || 'Digitally generated by Skupadi',
        showPoweredBy: currentConfig?.showPoweredBy ?? true,
        
        // Late Payment Settings
        showLateFeeWarning: currentConfig?.showLateFeeWarning ?? true,
        lateFeeWarningText: currentConfig?.lateFeeWarningText || 'Late payment fees may apply after due date.',
        
        // Contact Information
        showContactInfo: currentConfig?.showContactInfo ?? true,
        contactPersonName: currentConfig?.contactPersonName || '',
        contactPersonTitle: currentConfig?.contactPersonTitle || 'Bursar'
      });
    }
  }, [currentConfig, reset]);

  // Options for dropdowns
  const colorSchemeOptions = [
    { value: 'blue', label: 'Professional Blue' },
    { value: 'green', label: 'Academic Green' },
    { value: 'purple', label: 'Royal Purple' },
    { value: 'red', label: 'Elegant Red' },
    { value: 'gray', label: 'Classic Gray' },
    { value: 'orange', label: 'Vibrant Orange' },
    { value: 'custom', label: 'Custom Colors' }
  ];

  const templateOptions = [
    { value: 'standard', label: 'Standard Template' },
    { value: 'modern', label: 'Modern Template' },
    { value: 'classic', label: 'Classic Template' },
    { value: 'minimalist', label: 'Minimalist Template' },
    { value: 'detailed', label: 'Detailed Template' },
    { value: 'corporate', label: 'Corporate Template' }
  ];

  const logoPositionOptions = [
    { value: 'top-left', label: 'Top Left' },
    { value: 'top-center', label: 'Top Center' },
    { value: 'top-right', label: 'Top Right' },
    { value: 'header-left', label: 'Header Left' },
    { value: 'header-right', label: 'Header Right' }
  ];

  const watermarkPositionOptions = [
    { value: 'center-middle', label: 'Center Middle' },
    { value: 'top-left', label: 'Top Left' },
    { value: 'top-right', label: 'Top Right' },
    { value: 'bottom-left', label: 'Bottom Left' },
    { value: 'bottom-right', label: 'Bottom Right' },
    { value: 'behind-content', label: 'Behind Content' }
  ];

  const headerStyleOptions = [
    { value: 'standard', label: 'Standard Header' },
    { value: 'minimal', label: 'Minimal Header' },
    { value: 'detailed', label: 'Detailed Header' },
    { value: 'branded', label: 'Branded Header' }
  ];

  const footerStyleOptions = [
    { value: 'standard', label: 'Standard Footer' },
    { value: 'minimal', label: 'Minimal Footer' },
    { value: 'detailed', label: 'Detailed Footer' },
    { value: 'branded', label: 'Branded Footer' }
  ];

  const qrCodeSizeOptions = [
    { value: 'small', label: 'Small (80x80px)' },
    { value: 'medium', label: 'Medium (120x120px)' },
    { value: 'large', label: 'Large (150x150px)' }
  ];

  const qrCodePositionOptions = [
    { value: 'top-left', label: 'Top Left' },
    { value: 'top-right', label: 'Top Right' },
    { value: 'bottom-left', label: 'Bottom Left' },
    { value: 'bottom-right', label: 'Bottom Right' },
    { value: 'sidebar', label: 'Sidebar' }
  ];

  const currencyFormatOptions = [
    { value: 'NGN', label: 'Nigerian Naira (₦)' },
    { value: 'USD', label: 'US Dollar ($)' },
    { value: 'EUR', label: 'Euro (€)' },
    { value: 'GBP', label: 'British Pound (£)' }
  ];

  const dateFormatOptions = [
    { value: 'DD/MM/YYYY', label: 'DD/MM/YYYY' },
    { value: 'MM/DD/YYYY', label: 'MM/DD/YYYY' },
    { value: 'YYYY-MM-DD', label: 'YYYY-MM-DD' },
    { value: 'DD-MM-YYYY', label: 'DD-MM-YYYY' }
  ];

  const onSubmit = (data) => {
    const invoiceConfig = {
      invoiceElements: {
        studentName: data?.showStudentName,
        studentId: data?.showStudentId,
        studentClass: data?.showStudentClass,
        parentInfo: data?.showParentInfo,
        schoolName: data?.showSchoolName,
        schoolAddress: data?.showSchoolAddress,
        schoolEmail: data?.showSchoolEmail,
        schoolPhone: data?.showSchoolPhone,
        invoiceNumber: data?.showInvoiceNumber,
        issueDate: data?.showIssueDate,
        dueDate: data?.showDueDate,
        sessionTerm: data?.showSessionTerm,
        paymentBreakdown: data?.showPaymentBreakdown,
        qrCode: data?.showQrCode,
        watermark: data?.showWatermark,
        skupadiBranding: data?.showSkupadiBranding,
        paymentInstructions: data?.showPaymentInstructions,
        installmentOptions: data?.showInstallmentOptions
      },
      invoiceColorScheme: data?.invoiceColorScheme,
      invoiceTemplate: data?.invoiceTemplate,
      logoPosition: data?.logoPosition,
      watermarkPosition: data?.watermarkPosition,
      headerStyle: data?.headerStyle,
      footerStyle: data?.footerStyle,
      invoiceTitle: data?.invoiceTitle,
      paymentInstructions: data?.paymentInstructions,
      footerMessage: data?.footerMessage,
      issuerName: data?.issuerName,
      showTermsConditions: data?.showTermsConditions,
      termsConditions: data?.termsConditions,
      showBankDetails: data?.showBankDetails,
      showPaymentMethods: data?.showPaymentMethods,
      showOnlinePaymentLink: data?.showOnlinePaymentLink,
      qrCodeSize: data?.qrCodeSize,
      qrCodePosition: data?.qrCodePosition,
      includeInvoiceId: data?.includeInvoiceId,
      includePaymentReference: data?.includePaymentReference,
      includeVerificationUrl: data?.includeVerificationUrl,
      showItemQuantity: data?.showItemQuantity,
      showUnitPrices: data?.showUnitPrices,
      showSubtotal: data?.showSubtotal,
      showDiscounts: data?.showDiscounts,
      showTaxes: data?.showTaxes,
      showLateFees: data?.showLateFees,
      currencyFormat: data?.currencyFormat,
      dateFormat: data?.dateFormat,
      includeDigitalSignature: data?.includeDigitalSignature,
      signatureText: data?.signatureText,
      showPoweredBy: data?.showPoweredBy,
      showLateFeeWarning: data?.showLateFeeWarning,
      lateFeeWarningText: data?.lateFeeWarningText,
      showContactInfo: data?.showContactInfo,
      contactPersonName: data?.contactPersonName,
      contactPersonTitle: data?.contactPersonTitle
    };

    onSave(invoiceConfig);
    onClose();
  };

  const handlePreset = (preset) => {
    const presets = {
      minimal: {
        showStudentName: true,
        showInvoiceNumber: true,
        showDueDate: true,
        showPaymentBreakdown: true,
        showPaymentInstructions: true,
        showQrCode: false,
        showParentInfo: false,
        showSchoolAddress: false,
        showTermsConditions: false,
        invoiceTemplate: 'minimalist',
        headerStyle: 'minimal',
        footerStyle: 'minimal'
      },
      standard: {
        showStudentName: true,
        showStudentId: true,
        showStudentClass: true,
        showInvoiceNumber: true,
        showIssueDate: true,
        showDueDate: true,
        showPaymentBreakdown: true,
        showPaymentInstructions: true,
        showBankDetails: true,
        showQrCode: false,
        showParentInfo: true,
        invoiceTemplate: 'standard',
        headerStyle: 'standard',
        footerStyle: 'standard'
      },
      detailed: {
        showStudentName: true,
        showStudentId: true,
        showStudentClass: true,
        showParentInfo: true,
        showSchoolAddress: true,
        showSchoolEmail: true,
        showSchoolPhone: true,
        showInvoiceNumber: true,
        showIssueDate: true,
        showDueDate: true,
        showSessionTerm: true,
        showPaymentBreakdown: true,
        showPaymentInstructions: true,
        showBankDetails: true,
        showPaymentMethods: true,
        showTermsConditions: true,
        showQrCode: true,
        showWatermark: true,
        showLateFeeWarning: true,
        showContactInfo: true,
        invoiceTemplate: 'detailed',
        headerStyle: 'detailed',
        footerStyle: 'detailed'
      }
    };

    const selectedPreset = presets?.[preset];
    Object.keys(selectedPreset)?.forEach(key => {
      setValue(key, selectedPreset?.[key]);
    });
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-50">
      <div className="bg-card rounded-lg border border-border max-w-5xl w-full max-h-[90vh] overflow-hidden flex flex-col">
        {/* Header */}
        <div className="flex items-center justify-between p-6 border-b border-border">
          <div>
            <h2 className="text-xl font-semibold text-foreground flex items-center space-x-2">
              <Icon name="FileText" size={20} className="text-primary" />
              <span>Invoice Configuration</span>
            </h2>
            <p className="text-sm text-muted-foreground mt-1">
              Customize what appears on your school's fee invoices and their layout
            </p>
          </div>
          <Button variant="ghost" size="icon" onClick={onClose}>
            <Icon name="X" size={20} />
          </Button>
        </div>

        {/* Quick Presets */}
        <div className="px-6 py-4 border-b border-border bg-muted/30">
          <div className="flex items-center space-x-4">
            <span className="text-sm font-medium text-foreground">Quick Presets:</span>
            <div className="flex items-center space-x-2">
              <Button
                type="button"
                variant="outline"
                size="sm"
                onClick={() => handlePreset('minimal')}
              >
                Minimal
              </Button>
              <Button
                type="button"
                variant="outline"
                size="sm"
                onClick={() => handlePreset('standard')}
              >
                Standard
              </Button>
              <Button
                type="button"
                variant="outline"
                size="sm"
                onClick={() => handlePreset('detailed')}
              >
                Detailed
              </Button>
            </div>
          </div>
        </div>

        {/* Tab Navigation */}
        <div className="border-b border-border">
          <nav className="flex space-x-6 px-6">
            <button
              onClick={() => setActiveTab('elements')}
              className={`py-4 px-1 border-b-2 font-medium text-sm transition-colors duration-200 ${
                activeTab === 'elements' ? 'border-primary text-primary' : 'border-transparent text-muted-foreground hover:text-foreground'
              }`}
            >
              <div className="flex items-center space-x-2">
                <Icon name="List" size={16} />
                <span>Elements</span>
              </div>
            </button>
            
            <button
              onClick={() => setActiveTab('layout')}
              className={`py-4 px-1 border-b-2 font-medium text-sm transition-colors duration-200 ${
                activeTab === 'layout' ? 'border-primary text-primary' : 'border-transparent text-muted-foreground hover:text-foreground'
              }`}
            >
              <div className="flex items-center space-x-2">
                <Icon name="Layout" size={16} />
                <span>Layout & Style</span>
              </div>
            </button>
            
            <button
              onClick={() => setActiveTab('payment')}
              className={`py-4 px-1 border-b-2 font-medium text-sm transition-colors duration-200 ${
                activeTab === 'payment' ? 'border-primary text-primary' : 'border-transparent text-muted-foreground hover:text-foreground'
              }`}
            >
              <div className="flex items-center space-x-2">
                <Icon name="CreditCard" size={16} />
                <span>Payment Info</span>
              </div>
            </button>

            <button
              onClick={() => setActiveTab('advanced')}
              className={`py-4 px-1 border-b-2 font-medium text-sm transition-colors duration-200 ${
                activeTab === 'advanced' ? 'border-primary text-primary' : 'border-transparent text-muted-foreground hover:text-foreground'
              }`}
            >
              <div className="flex items-center space-x-2">
                <Icon name="Sliders" size={16} />
                <span>Advanced</span>
              </div>
            </button>
          </nav>
        </div>

        {/* Content */}
        <form onSubmit={handleSubmit(onSubmit)} className="flex-1 overflow-hidden flex flex-col">
          <div className="flex-1 overflow-y-auto p-6">
            {/* Elements Tab */}
            {activeTab === 'elements' && (
              <div className="space-y-6">
                {/* Student Information Elements */}
                <div className="bg-muted/30 rounded-lg p-4">
                  <h3 className="font-semibold text-foreground mb-4 flex items-center space-x-2">
                    <Icon name="User" size={16} className="text-primary" />
                    <span>Student Information</span>
                  </h3>
                  <div className="grid grid-cols-2 md:grid-cols-3 gap-4">
                    <Checkbox
                      id="showStudentName"
                      label="Student Name"
                      checked={watchedValues?.showStudentName}
                      onChange={(checked) => setValue('showStudentName', checked)}
                    />
                    <Checkbox
                      id="showStudentId"
                      label="Student ID"
                      checked={watchedValues?.showStudentId}
                      onChange={(checked) => setValue('showStudentId', checked)}
                    />
                    <Checkbox
                      id="showStudentClass"
                      label="Student Class"
                      checked={watchedValues?.showStudentClass}
                      onChange={(checked) => setValue('showStudentClass', checked)}
                    />
                    <Checkbox
                      id="showParentInfo"
                      label="Parent/Guardian Info"
                      checked={watchedValues?.showParentInfo}
                      onChange={(checked) => setValue('showParentInfo', checked)}
                    />
                  </div>
                </div>

                {/* School Information Elements */}
                <div className="bg-muted/30 rounded-lg p-4">
                  <h3 className="font-semibold text-foreground mb-4 flex items-center space-x-2">
                    <Icon name="School" size={16} className="text-primary" />
                    <span>School Information</span>
                  </h3>
                  <div className="grid grid-cols-2 md:grid-cols-3 gap-4">
                    <Checkbox
                      id="showSchoolName"
                      label="School Name"
                      checked={watchedValues?.showSchoolName}
                      onChange={(checked) => setValue('showSchoolName', checked)}
                    />
                    <Checkbox
                      id="showSchoolAddress"
                      label="School Address"
                      checked={watchedValues?.showSchoolAddress}
                      onChange={(checked) => setValue('showSchoolAddress', checked)}
                    />
                    <Checkbox
                      id="showSchoolEmail"
                      label="School Email"
                      checked={watchedValues?.showSchoolEmail}
                      onChange={(checked) => setValue('showSchoolEmail', checked)}
                    />
                    <Checkbox
                      id="showSchoolPhone"
                      label="School Phone"
                      checked={watchedValues?.showSchoolPhone}
                      onChange={(checked) => setValue('showSchoolPhone', checked)}
                    />
                  </div>
                </div>

                {/* Invoice & Academic Elements */}
                <div className="bg-muted/30 rounded-lg p-4">
                  <h3 className="font-semibold text-foreground mb-4 flex items-center space-x-2">
                    <Icon name="FileText" size={16} className="text-primary" />
                    <span>Invoice & Academic Information</span>
                  </h3>
                  <div className="grid grid-cols-2 md:grid-cols-3 gap-4">
                    <Checkbox
                      id="showInvoiceNumber"
                      label="Invoice Number"
                      checked={watchedValues?.showInvoiceNumber}
                      onChange={(checked) => setValue('showInvoiceNumber', checked)}
                    />
                    <Checkbox
                      id="showIssueDate"
                      label="Issue Date"
                      checked={watchedValues?.showIssueDate}
                      onChange={(checked) => setValue('showIssueDate', checked)}
                    />
                    <Checkbox
                      id="showDueDate"
                      label="Due Date"
                      checked={watchedValues?.showDueDate}
                      onChange={(checked) => setValue('showDueDate', checked)}
                    />
                    <Checkbox
                      id="showSessionTerm"
                      label="Session & Term"
                      checked={watchedValues?.showSessionTerm}
                      onChange={(checked) => setValue('showSessionTerm', checked)}
                    />
                    <Checkbox
                      id="showPaymentBreakdown"
                      label="Payment Breakdown"
                      checked={watchedValues?.showPaymentBreakdown}
                      onChange={(checked) => setValue('showPaymentBreakdown', checked)}
                    />
                    <Checkbox
                      id="showInstallmentOptions"
                      label="Installment Options"
                      checked={watchedValues?.showInstallmentOptions}
                      onChange={(checked) => setValue('showInstallmentOptions', checked)}
                    />
                  </div>
                </div>

                {/* Visual & Additional Elements */}
                <div className="bg-muted/30 rounded-lg p-4">
                  <h3 className="font-semibold text-foreground mb-4 flex items-center space-x-2">
                    <Icon name="Eye" size={16} className="text-primary" />
                    <span>Visual & Additional Elements</span>
                  </h3>
                  <div className="grid grid-cols-2 md:grid-cols-3 gap-4">
                    <Checkbox
                      id="showPaymentInstructions"
                      label="Payment Instructions"
                      checked={watchedValues?.showPaymentInstructions}
                      onChange={(checked) => setValue('showPaymentInstructions', checked)}
                    />
                    <Checkbox
                      id="showQrCode"
                      label="QR Code"
                      checked={watchedValues?.showQrCode}
                      onChange={(checked) => setValue('showQrCode', checked)}
                    />
                    <Checkbox
                      id="showWatermark"
                      label="Watermark"
                      checked={watchedValues?.showWatermark}
                      onChange={(checked) => setValue('showWatermark', checked)}
                    />
                    <Checkbox
                      id="showSkupadiBranding"
                      label="Skupadi Branding"
                      checked={watchedValues?.showSkupadiBranding}
                      onChange={(checked) => setValue('showSkupadiBranding', checked)}
                    />
                    <Checkbox
                      id="showContactInfo"
                      label="Contact Person Info"
                      checked={watchedValues?.showContactInfo}
                      onChange={(checked) => setValue('showContactInfo', checked)}
                    />
                    <Checkbox
                      id="showLateFeeWarning"
                      label="Late Fee Warning"
                      checked={watchedValues?.showLateFeeWarning}
                      onChange={(checked) => setValue('showLateFeeWarning', checked)}
                    />
                  </div>
                </div>
              </div>
            )}

            {/* Layout & Style Tab */}
            {activeTab === 'layout' && (
              <div className="space-y-6">
                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                  <Select
                    label="Invoice Template"
                    options={templateOptions}
                    value={watchedValues?.invoiceTemplate}
                    onChange={(value) => setValue('invoiceTemplate', value)}
                    placeholder="Select template"
                  />
                  <Select
                    label="Color Scheme"
                    options={colorSchemeOptions}
                    value={watchedValues?.invoiceColorScheme}
                    onChange={(value) => setValue('invoiceColorScheme', value)}
                    placeholder="Select color scheme"
                  />
                  <Select
                    label="Logo Position"
                    options={logoPositionOptions}
                    value={watchedValues?.logoPosition}
                    onChange={(value) => setValue('logoPosition', value)}
                    placeholder="Select logo position"
                  />
                  <Select
                    label="Watermark Position"
                    options={watermarkPositionOptions}
                    value={watchedValues?.watermarkPosition}
                    onChange={(value) => setValue('watermarkPosition', value)}
                    placeholder="Select watermark position"
                  />
                  <Select
                    label="Header Style"
                    options={headerStyleOptions}
                    value={watchedValues?.headerStyle}
                    onChange={(value) => setValue('headerStyle', value)}
                    placeholder="Select header style"
                  />
                  <Select
                    label="Footer Style"
                    options={footerStyleOptions}
                    value={watchedValues?.footerStyle}
                    onChange={(value) => setValue('footerStyle', value)}
                    placeholder="Select footer style"
                  />
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                  <Input
                    label="Invoice Title"
                    {...register('invoiceTitle')}
                    placeholder="SCHOOL FEE INVOICE"
                  />
                  <Input
                    label="Footer Message"
                    {...register('footerMessage')}
                    placeholder="Thank you for choosing our school!"
                  />
                  <Input
                    label="Issuer Name"
                    {...register('issuerName')}
                    placeholder="Skupadi System"
                  />
                </div>

                {/* Contact Information */}
                {watchedValues?.showContactInfo && (
                  <div className="bg-muted/30 rounded-lg p-4">
                    <h3 className="font-semibold text-foreground mb-4">Contact Person Information</h3>
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                      <Input
                        label="Contact Person Name"
                        {...register('contactPersonName')}
                        placeholder="e.g., John Doe"
                      />
                      <Input
                        label="Contact Person Title"
                        {...register('contactPersonTitle')}
                        placeholder="e.g., Bursar"
                      />
                    </div>
                  </div>
                )}
              </div>
            )}

            {/* Payment Info Tab */}
            {activeTab === 'payment' && (
              <div className="space-y-6">
                <div className="bg-info/10 border border-info/20 rounded-lg p-4">
                  <div className="flex items-center space-x-2 mb-2">
                    <Icon name="Info" size={16} className="text-info" />
                    <h4 className="text-sm font-medium text-foreground">Payment Information Configuration</h4>
                  </div>
                  <p className="text-sm text-muted-foreground">
                    Configure what payment-related information appears on invoices to help parents make payments easily.
                  </p>
                </div>

                {/* Payment Options */}
                <div className="bg-muted/30 rounded-lg p-4">
                  <h3 className="font-semibold text-foreground mb-4">Payment Information Display</h3>
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <Checkbox
                      id="showBankDetails"
                      label="Bank Details"
                      checked={watchedValues?.showBankDetails}
                      onChange={(checked) => setValue('showBankDetails', checked)}
                      description="Show bank account information for transfers"
                    />
                    <Checkbox
                      id="showPaymentMethods"
                      label="Payment Methods"
                      checked={watchedValues?.showPaymentMethods}
                      onChange={(checked) => setValue('showPaymentMethods', checked)}
                      description="Display available payment options"
                    />
                    <Checkbox
                      id="showOnlinePaymentLink"
                      label="Online Payment Link"
                      checked={watchedValues?.showOnlinePaymentLink}
                      onChange={(checked) => setValue('showOnlinePaymentLink', checked)}
                      description="Include link for online payments"
                    />
                    <Checkbox
                      id="showTermsConditions"
                      label="Terms & Conditions"
                      checked={watchedValues?.showTermsConditions}
                      onChange={(checked) => setValue('showTermsConditions', checked)}
                      description="Display payment terms and conditions"
                    />
                  </div>
                </div>

                {/* Payment Instructions */}
                <div className="space-y-4">
                  <h3 className="font-semibold text-foreground">Payment Instructions</h3>
                  <textarea
                    {...register('paymentInstructions')}
                    className="w-full p-3 border border-input rounded-md bg-background text-foreground resize-none"
                    rows={3}
                    placeholder="Please make payment before the due date to avoid late fees."
                  />
                </div>

                {/* Terms & Conditions */}
                {watchedValues?.showTermsConditions && (
                  <div className="space-y-4">
                    <h3 className="font-semibold text-foreground">Terms & Conditions</h3>
                    <textarea
                      {...register('termsConditions')}
                      className="w-full p-3 border border-input rounded-md bg-background text-foreground resize-none"
                      rows={4}
                      placeholder="Payment terms and conditions apply..."
                    />
                  </div>
                )}

                {/* Late Fee Warning */}
                {watchedValues?.showLateFeeWarning && (
                  <div className="space-y-4">
                    <h3 className="font-semibold text-foreground">Late Fee Warning Text</h3>
                    <Input
                      {...register('lateFeeWarningText')}
                      placeholder="Late payment fees may apply after due date."
                    />
                  </div>
                )}

                {/* QR Code Configuration */}
                {watchedValues?.showQrCode && (
                  <div className="bg-muted/30 rounded-lg p-4">
                    <h3 className="font-semibold text-foreground mb-4">QR Code Configuration</h3>
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                      <Select
                        label="QR Code Size"
                        options={qrCodeSizeOptions}
                        value={watchedValues?.qrCodeSize}
                        onChange={(value) => setValue('qrCodeSize', value)}
                        placeholder="Select QR code size"
                      />
                      <Select
                        label="QR Code Position"
                        options={qrCodePositionOptions}
                        value={watchedValues?.qrCodePosition}
                        onChange={(value) => setValue('qrCodePosition', value)}
                        placeholder="Select QR code position"
                      />
                    </div>
                    
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mt-4">
                      <Checkbox
                        id="includeInvoiceId"
                        label="Include Invoice ID"
                        checked={watchedValues?.includeInvoiceId}
                        onChange={(checked) => setValue('includeInvoiceId', checked)}
                        description="Include invoice ID in QR code"
                      />
                      <Checkbox
                        id="includePaymentReference"
                        label="Include Payment Reference"
                        checked={watchedValues?.includePaymentReference}
                        onChange={(checked) => setValue('includePaymentReference', checked)}
                        description="Include payment reference in QR code"
                      />
                      <Checkbox
                        id="includeVerificationUrl"
                        label="Include Verification URL"
                        checked={watchedValues?.includeVerificationUrl}
                        onChange={(checked) => setValue('includeVerificationUrl', checked)}
                        description="Include link to online verification"
                      />
                    </div>
                  </div>
                )}
              </div>
            )}

            {/* Advanced Tab */}
            {activeTab === 'advanced' && (
              <div className="space-y-6">
                {/* Payment Display Options */}
                <div className="bg-muted/30 rounded-lg p-4">
                  <h3 className="font-semibold text-foreground mb-4 flex items-center space-x-2">
                    <Icon name="Calculator" size={16} className="text-primary" />
                    <span>Payment Display Options</span>
                  </h3>
                  <div className="grid grid-cols-2 md:grid-cols-3 gap-4">
                    <Checkbox
                      id="showItemQuantity"
                      label="Item Quantities"
                      checked={watchedValues?.showItemQuantity}
                      onChange={(checked) => setValue('showItemQuantity', checked)}
                    />
                    <Checkbox
                      id="showUnitPrices"
                      label="Unit Prices"
                      checked={watchedValues?.showUnitPrices}
                      onChange={(checked) => setValue('showUnitPrices', checked)}
                    />
                    <Checkbox
                      id="showSubtotal"
                      label="Subtotal"
                      checked={watchedValues?.showSubtotal}
                      onChange={(checked) => setValue('showSubtotal', checked)}
                    />
                    <Checkbox
                      id="showDiscounts"
                      label="Discounts"
                      checked={watchedValues?.showDiscounts}
                      onChange={(checked) => setValue('showDiscounts', checked)}
                    />
                    <Checkbox
                      id="showTaxes"
                      label="Taxes"
                      checked={watchedValues?.showTaxes}
                      onChange={(checked) => setValue('showTaxes', checked)}
                    />
                    <Checkbox
                      id="showLateFees"
                      label="Late Fees"
                      checked={watchedValues?.showLateFees}
                      onChange={(checked) => setValue('showLateFees', checked)}
                    />
                  </div>
                </div>

                {/* Format Settings */}
                <div className="bg-muted/30 rounded-lg p-4">
                  <h3 className="font-semibold text-foreground mb-4 flex items-center space-x-2">
                    <Icon name="Settings" size={16} className="text-primary" />
                    <span>Format Settings</span>
                  </h3>
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                    <Select
                      label="Currency Format"
                      options={currencyFormatOptions}
                      value={watchedValues?.currencyFormat}
                      onChange={(value) => setValue('currencyFormat', value)}
                      placeholder="Select currency"
                    />
                    <Select
                      label="Date Format"
                      options={dateFormatOptions}
                      value={watchedValues?.dateFormat}
                      onChange={(value) => setValue('dateFormat', value)}
                      placeholder="Select date format"
                    />
                  </div>
                </div>

                {/* Signature Settings */}
                <div className="bg-muted/30 rounded-lg p-4">
                  <h3 className="font-semibold text-foreground mb-4 flex items-center space-x-2">
                    <Icon name="PenTool" size={16} className="text-primary" />
                    <span>Signature & Branding</span>
                  </h3>
                  <div className="space-y-4">
                    <Checkbox
                      id="includeDigitalSignature"
                      label="Include Digital Signature"
                      checked={watchedValues?.includeDigitalSignature}
                      onChange={(checked) => setValue('includeDigitalSignature', checked)}
                      description="Add digital signature for authenticity"
                    />
                    {watchedValues?.includeDigitalSignature && (
                      <Input
                        label="Signature Text"
                        {...register('signatureText')}
                        placeholder="Digitally generated by Skupadi"
                      />
                    )}
                    <Checkbox
                      id="showPoweredBy"
                      label="Show 'Powered by Skupadi'"
                      checked={watchedValues?.showPoweredBy}
                      onChange={(checked) => setValue('showPoweredBy', checked)}
                      description="Display Skupadi attribution"
                    />
                  </div>
                </div>

                {/* Invoice Preview */}
                <div className="bg-muted/30 rounded-lg p-6">
                  <div className="flex items-center space-x-2 mb-4">
                    <Icon name="Eye" size={16} className="text-primary" />
                    <h3 className="text-base font-medium text-foreground">Invoice Preview</h3>
                  </div>
                  
                  {/* Sample Invoice Preview */}
                  <div className="bg-white rounded-lg border border-border p-6 max-w-md mx-auto shadow-lg">
                    {/* Header */}
                    <div className="text-center mb-4">
                      <h3 className="text-lg font-bold text-gray-800">
                        {watchedValues?.invoiceTitle || 'SCHOOL FEE INVOICE'}
                      </h3>
                      <p className="text-xs text-gray-600">Sample School Name</p>
                      {watchedValues?.showSchoolAddress && (
                        <p className="text-xs text-gray-600">School Address</p>
                      )}
                    </div>
                    
                    {/* Sample Content */}
                    <div className="space-y-3 text-xs">
                      {/* Student Information */}
                      {watchedValues?.showStudentName && (
                        <div className="bg-gray-50 p-2 rounded">
                          <h5 className="font-semibold text-gray-700 mb-1">Student Information</h5>
                          <div className="space-y-1">
                            <div className="flex justify-between">
                              <span>Name:</span>
                              <span>John Doe</span>
                            </div>
                            {watchedValues?.showStudentId && (
                              <div className="flex justify-between">
                                <span>Student ID:</span>
                                <span>STD-2024-001</span>
                              </div>
                            )}
                            {watchedValues?.showStudentClass && (
                              <div className="flex justify-between">
                                <span>Class:</span>
                                <span>JSS 2A</span>
                              </div>
                            )}
                          </div>
                        </div>
                      )}

                      {/* Invoice Details */}
                      <div className="bg-gray-50 p-2 rounded">
                        <h5 className="font-semibold text-gray-700 mb-1">Invoice Details</h5>
                        <div className="space-y-1">
                          {watchedValues?.showInvoiceNumber && (
                            <div className="flex justify-between">
                              <span>Invoice #:</span>
                              <span>INV-2024-001</span>
                            </div>
                          )}
                          {watchedValues?.showIssueDate && (
                            <div className="flex justify-between">
                              <span>Issue Date:</span>
                              <span>01/09/2024</span>
                            </div>
                          )}
                          {watchedValues?.showDueDate && (
                            <div className="flex justify-between">
                              <span>Due Date:</span>
                              <span>30/09/2024</span>
                            </div>
                          )}
                        </div>
                      </div>

                      {/* Payment Breakdown */}
                      {watchedValues?.showPaymentBreakdown && (
                        <div className="bg-gray-50 p-2 rounded">
                          <h5 className="font-semibold text-gray-700 mb-1">Fee Breakdown</h5>
                          <table className="w-full text-xs">
                            <thead>
                              <tr className="border-b">
                                <th className="text-left">Item</th>
                                <th className="text-right">Amount</th>
                              </tr>
                            </thead>
                            <tbody>
                              <tr>
                                <td>Tuition Fee</td>
                                <td className="text-right">₦30,000</td>
                              </tr>
                              <tr>
                                <td>Development Levy</td>
                                <td className="text-right">₦15,000</td>
                              </tr>
                            </tbody>
                          </table>
                        </div>
                      )}

                      {/* Payment Instructions */}
                      {watchedValues?.showPaymentInstructions && (
                        <div className="bg-yellow-50 p-2 rounded border border-yellow-200">
                          <p className="text-xs text-gray-700">
                            {watchedValues?.paymentInstructions || 'Please make payment before the due date.'}
                          </p>
                        </div>
                      )}

                      {/* Total */}
                      <div className="bg-primary/10 p-2 rounded">
                        <div className="flex justify-between font-semibold">
                          <span>Total Amount:</span>
                          <span>₦45,000</span>
                        </div>
                      </div>

                      {/* QR Code Section */}
                      {watchedValues?.showQrCode && (
                        <div className="flex justify-between items-center border-t pt-2">
                          <div>
                            <p className="text-xs text-gray-500">Payment QR Code</p>
                            <p className="text-xs text-primary">Scan for quick payment</p>
                          </div>
                          <div className="w-12 h-12 bg-gray-200 rounded flex items-center justify-center">
                            <Icon name="QrCode" size={16} className="text-gray-500" />
                          </div>
                        </div>
                      )}
                    </div>
                    
                    {/* Footer */}
                    <div className="mt-4 pt-3 border-t border-gray-200 text-center text-xs text-gray-500">
                      <p>{watchedValues?.footerMessage || 'Thank you for choosing our school!'}</p>
                      {watchedValues?.showPoweredBy && (
                        <div className="flex items-center justify-center space-x-1 mt-1">
                          <Icon name="GraduationCap" size={10} className="text-primary" />
                          <span className="text-primary font-medium">Powered by Skupadi</span>
                        </div>
                      )}
                    </div>
                  </div>
                  
                  <p className="text-xs text-muted-foreground text-center mt-4">
                    This preview shows how your configured invoice will appear to parents and students.
                  </p>
                </div>
              </div>
            )}
          </div>

          {/* Footer Actions */}
          <div className="border-t border-border p-6 bg-muted/30">
            {/* Astroidegita Technologies Branding Footer */}
            <div className="flex items-center justify-center mb-6 py-4 border-t border-border bg-gradient-to-r from-blue-50 to-indigo-50 rounded-lg">
              <div className="text-center space-y-2">
                <div className="flex items-center justify-center space-x-3">
                  <img 
                    src="/assets/images/ChatGPT_Image_Jun_19_2025_03_06_50_PM_prev_ui_1-1758892592480.png" 
                    alt="Astroidegita Technologies" 
                    className="h-8 w-8 object-contain"
                  />
                  <div>
                    <p className="text-sm font-medium" style={{ color: '#081C48' }}>
                      ©2025 Astroidegita Technologies LTD (RC 8354011).
                    </p>
                    <p className="text-xs" style={{ color: '#081C48' }}>
                      If you have any questions or complaints about this transaction, please contact our support team at{' '}
                      <span className="font-bold">support@skupadi.com</span>
                    </p>
                  </div>
                </div>
              </div>
            </div>

            <div className="flex items-center justify-between">
              <div className="text-sm text-muted-foreground">
                Configure invoice elements to match your school's requirements
              </div>
              <div className="flex items-center space-x-3">
                <Button type="button" variant="outline" onClick={onClose}>
                  Cancel
                </Button>
                <Button type="submit" variant="default">
                  Save Configuration
                </Button>
              </div>
            </div>
          </div>
        </form>
      </div>
    </div>
  );
};

export default InvoiceConfigurationModal;