import jsPDF from 'jspdf';


/**
 * Professional PDF Generation Service for Skupadi School Management System
 * Generates branded invoices, receipts, and reports with school customization
 */
class PDFGenerationService {
  constructor() {
    // PDF Configuration
    this.defaultConfig = {
      format: 'a4',
      orientation: 'portrait',
      unit: 'mm',
      compress: true,
      margins: {
        top: 20,
        bottom: 20,
        left: 15,
        right: 15
      }
    };

    // Default school branding (fallback)
    this.defaultBranding = {
      schoolName: 'School Name',
      schoolAddress: 'School Address',
      schoolPhone: '+234 XXX XXX XXXX',
      schoolEmail: 'info@school.edu.ng',
      schoolLogo: null,
      primaryColor: '#081C48', // Skupadi blue
      secondaryColor: '#EAEBEF',
      accentColor: '#22c55e'
    };
  }

  /**
   * Get school branding configuration
   */
  getSchoolBranding() {
    // In a real app, this would fetch from the school configuration
    const schoolConfig = localStorage?.getItem('schoolBranding');
    if (schoolConfig) {
      return JSON.parse(schoolConfig);
    }
    return this.defaultBranding;
  }

  /**
   * Get invoice configuration
   */
  getInvoiceConfig() {
    const invoiceConfig = localStorage?.getItem('invoiceConfiguration');
    if (invoiceConfig) {
      return JSON.parse(invoiceConfig);
    }
    
    // Default invoice configuration
    return {
      invoiceElements: {
        studentName: true,
        studentId: true,
        studentClass: true,
        parentInfo: true,
        schoolName: true,
        schoolAddress: true,
        schoolEmail: true,
        schoolPhone: true,
        invoiceNumber: true,
        issueDate: true,
        dueDate: true,
        sessionTerm: true,
        paymentBreakdown: true,
        qrCode: false,
        watermark: false,
        paymentInstructions: true
      },
      invoiceTemplate: 'standard',
      invoiceColorScheme: 'blue',
      logoPosition: 'top-center',
      headerStyle: 'standard',
      footerStyle: 'standard',
      invoiceTitle: 'SCHOOL FEE INVOICE',
      paymentInstructions: 'Please make payment before the due date to avoid late fees.',
      footerMessage: 'Thank you for choosing our school!',
      currencyFormat: 'NGN',
      dateFormat: 'DD/MM/YYYY',
      includeDigitalSignature: true,
      signatureText: 'Digitally generated by School Management System',
      showPoweredBy: false
    };
  }

  /**
   * Format currency with enhanced readability and consistency
   */
  formatCurrency(amount, config = {}) {
    const currencyFormat = config?.currencyFormat || 'NGN';
    
    // Ensure amount is a valid number
    const numericAmount = Number(amount) || 0;
    
    // Enhanced Nigerian Naira formatting for better readability
    if (currencyFormat === 'NGN') {
      return `₦${numericAmount?.toLocaleString('en-NG', {
        minimumFractionDigits: 2,
        maximumFractionDigits: 2
      })}`;
    }
    
    const formatters = {
      'USD': (val) => new Intl.NumberFormat('en-US', { 
        style: 'currency', 
        currency: 'USD',
        minimumFractionDigits: 2,
        maximumFractionDigits: 2
      })?.format(val),
      'EUR': (val) => new Intl.NumberFormat('de-DE', { 
        style: 'currency', 
        currency: 'EUR',
        minimumFractionDigits: 2,
        maximumFractionDigits: 2
      })?.format(val),
      'GBP': (val) => new Intl.NumberFormat('en-GB', { 
        style: 'currency', 
        currency: 'GBP',
        minimumFractionDigits: 2,
        maximumFractionDigits: 2
      })?.format(val)
    };

    const formatted = formatters?.[currencyFormat]?.(numericAmount);
    
    // Fallback to Nigerian formatting with improved readability
    if (!formatted) {
      return `₦${numericAmount?.toLocaleString('en-NG', {
        minimumFractionDigits: 2,
        maximumFractionDigits: 2
      })}`;
    }
    
    return formatted;
  }

  /**
   * Format date based on configuration
   */
  formatDate(dateString, config = {}) {
    const dateFormat = config?.dateFormat || 'DD/MM/YYYY';
    const date = new Date(dateString);
    
    const formatters = {
      'DD/MM/YYYY': () => date?.toLocaleDateString('en-GB'),
      'MM/DD/YYYY': () => date?.toLocaleDateString('en-US'),
      'YYYY-MM-DD': () => date?.toISOString()?.split('T')?.[0],
      'DD-MM-YYYY': () => date?.toLocaleDateString('en-GB')?.replace(/\//g, '-')
    };

    return formatters?.[dateFormat]?.() || date?.toLocaleDateString();
  }

  /**
   * Generate QR Code data URL
   */
  async generateQRCode(data, size = 100) {
    // Simple QR code placeholder - in production, use a proper QR code library
    const canvas = document?.createElement('canvas');
    const ctx = canvas?.getContext('2d');
    canvas.width = size;
    canvas.height = size;
    
    // Create a simple pattern as placeholder
    ctx.fillStyle = '#000000';
    ctx?.fillRect(0, 0, size, size);
    ctx.fillStyle = '#ffffff';
    ctx?.fillRect(10, 10, size - 20, size - 20);
    ctx.fillStyle = '#000000';
    ctx.font = '8px Arial';
    ctx.textAlign = 'center';
    ctx?.fillText('QR', size / 2, size / 2);
    
    return canvas?.toDataURL();
  }

  /**
   * Create PDF document with professional layout
   */
  async generateInvoicePDF(invoiceData, options = {}) {
    try {
      const branding = this.getSchoolBranding();
      const config = this.getInvoiceConfig();
      const doc = new jsPDF(this.defaultConfig);

      // Page dimensions
      const pageWidth = doc?.internal?.pageSize?.getWidth();
      const pageHeight = doc?.internal?.pageSize?.getHeight();
      const margin = this.defaultConfig?.margins?.left;
      const contentWidth = pageWidth - (margin * 2);

      let yPosition = margin;

      // Color scheme mapping
      const colorSchemes = {
        blue: { primary: '#081C48', secondary: '#3B82F6', accent: '#E3F2FD' },
        green: { primary: '#166534', secondary: '#22C55E', accent: '#F0FDF4' },
        purple: { primary: '#6B21A8', secondary: '#A855F7', accent: '#FAF5FF' },
        red: { primary: '#991B1B', secondary: '#EF4444', accent: '#FEF2F2' },
        gray: { primary: '#374151', secondary: '#6B7280', accent: '#F9FAFB' },
        orange: { primary: '#C2410C', secondary: '#F97316', accent: '#FFF7ED' }
      };

      const colors = colorSchemes?.[config?.invoiceColorScheme] || colorSchemes?.blue;

      // Header Section
      if (config?.invoiceElements?.schoolName || config?.logoPosition !== 'none') {
        // Header background
        doc?.setFillColor(colors?.primary);
        doc?.rect(0, 0, pageWidth, 40, 'F');

        // School logo (if available)
        if (branding?.schoolLogo && config?.logoPosition !== 'none') {
          try {
            const logoSize = 25;
            let logoX = margin;
            
            if (config?.logoPosition === 'top-center') {
              logoX = (pageWidth - logoSize) / 2;
            } else if (config?.logoPosition === 'top-right') {
              logoX = pageWidth - margin - logoSize;
            }
            
            doc?.addImage(branding?.schoolLogo, 'PNG', logoX, 8, logoSize, logoSize);
          } catch (error) {
            console.warn('Could not add school logo to PDF:', error);
          }
        }

        // School name and title
        doc?.setTextColor(255, 255, 255);
        doc?.setFontSize(20);
        doc?.setFont('helvetica', 'bold');
        
        let titleY = 20;
        if (config?.invoiceElements?.schoolName) {
          doc?.text(branding?.schoolName || 'School Name', pageWidth / 2, titleY, { align: 'center' });
          titleY += 8;
        }

        doc?.setFontSize(14);
        doc?.text(config?.invoiceTitle || 'SCHOOL FEE INVOICE', pageWidth / 2, titleY, { align: 'center' });

        yPosition = 50;
      }

      // School Information Section
      if (config?.invoiceElements?.schoolAddress || config?.invoiceElements?.schoolEmail || config?.invoiceElements?.schoolPhone) {
        doc?.setTextColor(0, 0, 0);
        doc?.setFontSize(10);
        doc?.setFont('helvetica', 'normal');

        const schoolInfo = [];
        if (config?.invoiceElements?.schoolAddress && branding?.schoolAddress) {
          schoolInfo?.push(branding?.schoolAddress);
        }
        if (config?.invoiceElements?.schoolPhone && branding?.schoolPhone) {
          schoolInfo?.push(`Tel: ${branding?.schoolPhone}`);
        }
        if (config?.invoiceElements?.schoolEmail && branding?.schoolEmail) {
          schoolInfo?.push(`Email: ${branding?.schoolEmail}`);
        }

        schoolInfo?.forEach((info, index) => {
          doc?.text(info, pageWidth / 2, yPosition + (index * 5), { align: 'center' });
        });

        yPosition += schoolInfo?.length * 5 + 10;
      }

      // Invoice Details Section
      if (config?.invoiceElements?.invoiceNumber || config?.invoiceElements?.issueDate || config?.invoiceElements?.dueDate) {
        // Section background
        doc?.setFillColor(colors?.accent);
        doc?.rect(margin, yPosition, contentWidth, 25, 'F');

        doc?.setTextColor(0, 0, 0);
        doc?.setFontSize(11);
        doc?.setFont('helvetica', 'bold');
        doc?.text('INVOICE DETAILS', margin + 5, yPosition + 8);

        let detailsY = yPosition + 15;
        doc?.setFont('helvetica', 'normal');
        doc?.setFontSize(10);

        const invoiceDetails = [];
        if (config?.invoiceElements?.invoiceNumber) {
          invoiceDetails?.push({ label: 'Invoice Number:', value: invoiceData?.id || 'N/A' });
        }
        if (config?.invoiceElements?.issueDate) {
          invoiceDetails?.push({ label: 'Issue Date:', value: this.formatDate(invoiceData?.issueDate || new Date(), config) });
        }
        if (config?.invoiceElements?.dueDate) {
          invoiceDetails?.push({ label: 'Due Date:', value: this.formatDate(invoiceData?.dueDate, config) });
        }
        if (config?.invoiceElements?.sessionTerm) {
          invoiceDetails?.push({ label: 'Session/Term:', value: '2024/2025 - First Term' });
        }

        invoiceDetails?.forEach((detail, index) => {
          let xPos = margin + 5 + (index % 2) * (contentWidth / 2);
          const yPos = detailsY + Math.floor(index / 2) * 6;
          doc?.setFont('helvetica', 'bold');
          doc?.text(detail?.label, xPos, yPos);
          doc?.setFont('helvetica', 'normal');
          doc?.text(detail?.value, xPos + 35, yPos);
        });

        yPosition += 30;
      }

      // Student Information Section
      if (config?.invoiceElements?.studentName || config?.invoiceElements?.studentId || config?.invoiceElements?.studentClass) {
        doc?.setFillColor(colors?.accent);
        doc?.rect(margin, yPosition, contentWidth, 25, 'F');

        doc?.setTextColor(0, 0, 0);
        doc?.setFontSize(11);
        doc?.setFont('helvetica', 'bold');
        doc?.text('STUDENT INFORMATION', margin + 5, yPosition + 8);

        let studentY = yPosition + 15;
        doc?.setFont('helvetica', 'normal');
        doc?.setFontSize(10);

        const studentInfo = [];
        if (config?.invoiceElements?.studentName) {
          studentInfo?.push({ label: 'Student Name:', value: invoiceData?.studentName || 'N/A' });
        }
        if (config?.invoiceElements?.studentId) {
          studentInfo?.push({ label: 'Student ID:', value: invoiceData?.studentId || 'N/A' });
        }
        if (config?.invoiceElements?.studentClass) {
          studentInfo?.push({ label: 'Class:', value: invoiceData?.class || 'N/A' });
        }

        studentInfo?.forEach((info, index) => {
          let xPos = margin + 5 + (index % 2) * (contentWidth / 2);
          const yPos = studentY + Math.floor(index / 2) * 6;
          doc?.setFont('helvetica', 'bold');
          doc?.text(info?.label, xPos, yPos);
          doc?.setFont('helvetica', 'normal');
          doc?.text(info?.value, xPos + 30, yPos);
        });

        yPosition += 30;
      }

      // Payment Breakdown Section
      if (config?.invoiceElements?.paymentBreakdown) {
        doc?.setFillColor(colors?.primary);
        doc?.rect(margin, yPosition, contentWidth, 10, 'F');

        doc?.setTextColor(255, 255, 255);
        doc?.setFontSize(12);
        doc?.setFont('helvetica', 'bold');
        doc?.text('FEE BREAKDOWN', margin + 5, yPosition + 7);

        yPosition += 15;

        // Enhanced table with proper column alignment
        doc?.setTextColor(0, 0, 0);
        doc?.setFont('helvetica', 'bold');
        doc?.setFontSize(10);
        
        // Table structure with improved spacing
        const descriptionX = margin + 5;
        const amountX = margin + contentWidth - 5;
        
        // Headers with proper alignment
        doc?.text('Description', descriptionX, yPosition + 5);
        doc?.text('Amount', amountX, yPosition + 5, { align: 'right' });

        // Table header line
        doc?.setLineWidth(0.5);
        doc?.line(margin, yPosition + 7, margin + contentWidth, yPosition + 7);

        yPosition += 12;

        // Fee items with enhanced formatting and consistent alignment
        const feeItems = invoiceData?.lineItems || [
          { description: 'Tuition Fee', amount: invoiceData?.amount * 0.7 },
          { description: 'Development Levy', amount: invoiceData?.amount * 0.2 },
          { description: 'Activity Fee', amount: invoiceData?.amount * 0.1 }
        ];

        doc?.setFont('helvetica', 'normal');
        doc?.setFontSize(10);
        
        feeItems?.forEach((item, index) => {
          // Alternating row background for better readability
          if (index % 2 === 1) {
            doc?.setFillColor(248, 249, 250); // Very light gray
            doc?.rect(margin, yPosition - 2, contentWidth, 8, 'F');
          }
          
          // Description aligned to left
          doc?.setTextColor(0, 0, 0);
          doc?.text(item?.description, descriptionX, yPosition + 2);
          
          // Amount formatted and right-aligned for perfect column alignment
          const formattedAmount = this.formatCurrency(item?.amount, config);
          doc?.text(formattedAmount, amountX, yPosition + 2, { align: 'right' });
          
          yPosition += 8;
        });

        // Subtotal section with enhanced spacing
        yPosition += 5;
        
        // Subtotal line
        doc?.setLineWidth(0.3);
        doc?.line(margin + contentWidth * 0.6, yPosition, margin + contentWidth, yPosition);
        yPosition += 8;

        // Calculate subtotal
        const subtotal = feeItems?.reduce((sum, item) => sum + item?.amount, 0);
        doc?.setFont('helvetica', 'normal');
        doc?.setFontSize(10);
        doc?.text('Subtotal:', descriptionX, yPosition);
        const formattedSubtotal = this.formatCurrency(subtotal, config);
        doc?.text(formattedSubtotal, amountX, yPosition, { align: 'right' });
        
        yPosition += 8;

        // Total section with enhanced visual emphasis
        doc?.setLineWidth(0.8);
        doc?.line(margin + contentWidth * 0.5, yPosition, margin + contentWidth, yPosition);
        yPosition += 10;

        // Total amount with enhanced formatting and perfect alignment
        doc?.setFont('helvetica', 'bold');
        doc?.setFontSize(14);
        doc?.setTextColor(colors?.primary);
        
        doc?.text('TOTAL AMOUNT:', descriptionX, yPosition);
        
        // Format and right-align the total amount with consistent formatting
        const totalFormatted = this.formatCurrency(invoiceData?.amount, config);
        doc?.text(totalFormatted, amountX, yPosition, { align: 'right' });
        
        // Add subtle emphasis background for total
        doc?.setFillColor(colors?.accent);
        const totalWidth = doc?.getTextWidth(totalFormatted);
        doc?.rect(amountX - totalWidth - 8, yPosition - 6, totalWidth + 16, 12, 'F');
        
        // Re-draw total amount on top of background
        doc?.setTextColor(colors?.primary);
        doc?.text(totalFormatted, amountX, yPosition, { align: 'right' });
        
        // Reset text color
        doc?.setTextColor(0, 0, 0);

        yPosition += 20;
      }

      // Payment Instructions Section
      if (config?.invoiceElements?.paymentInstructions) {
        doc?.setFillColor(255, 248, 220); // Light yellow background
        doc?.rect(margin, yPosition, contentWidth, 20, 'F');

        doc?.setTextColor(0, 0, 0);
        doc?.setFontSize(9);
        doc?.setFont('helvetica', 'bold');
        doc?.text('PAYMENT INSTRUCTIONS:', margin + 5, yPosition + 8);

        doc?.setFont('helvetica', 'normal');
        const instructions = config?.paymentInstructions?.split(' ');
        let line = '';
        let instructionY = yPosition + 14;

        instructions?.forEach((word) => {
          const testLine = line + word + ' ';
          const textWidth = doc?.getTextWidth(testLine);
          
          if (textWidth > contentWidth - 10 && line !== '') {
            doc?.text(line?.trim(), margin + 5, instructionY);
            line = word + ' ';
            instructionY += 5;
          } else {
            line = testLine;
          }
        });

        if (line) {
          doc?.text(line?.trim(), margin + 5, instructionY);
        }

        yPosition += 25;
      }

      // QR Code Section
      if (config?.invoiceElements?.qrCode) {
        try {
          const qrData = {
            invoiceId: invoiceData?.id,
            amount: invoiceData?.amount,
            studentName: invoiceData?.studentName,
            school: branding?.schoolName
          };
          
          const qrCodeImage = await this.generateQRCode(JSON.stringify(qrData), 80);
          doc?.addImage(qrCodeImage, 'PNG', pageWidth - margin - 25, yPosition, 25, 25);
          
          doc?.setFontSize(8);
          doc?.setFont('helvetica', 'normal');
          doc?.text('Scan for payment verification', pageWidth - margin - 25, yPosition + 30, { align: 'left' });
        } catch (error) {
          console.warn('Could not add QR code to PDF:', error);
        }
      }

      // Footer Section
      const footerY = pageHeight - 55; // Increased space for Astroidegita branding
      
      // Footer message with proper spacing
      if (config?.footerMessage) {
        doc?.setFontSize(10);
        doc?.setFont('helvetica', 'italic');
        doc?.setTextColor(100, 100, 100);
        doc?.text(config?.footerMessage, pageWidth / 2, footerY, { align: 'center' });
      }

      // Digital signature with increased spacing to prevent overlap
      if (config?.includeDigitalSignature) {
        doc?.setFontSize(8);
        doc?.setFont('helvetica', 'normal');
        // Increased spacing from 8 to 15 to prevent overlapping text
        doc?.text('Digitally generated by School Management System', pageWidth / 2, footerY + 15, { align: 'center' });
      }

      // Skupadi + Astroidegita Technologies Branding Section
      const skupadiY = pageHeight - 35;

      // Skupadi Copyright Text - Center aligned with #081C48 color
      doc?.setTextColor(8, 28, 72); // #081C48 color
      doc?.setFontSize(9);
      doc?.setFont('helvetica', 'normal');
      
      // Copyright line with Skupadi as product of Astroidegita
      doc?.text('©2025 Skupadi a product of Astroidegita Technologies LTD (RC 8354011).', pageWidth / 2, skupadiY + 8, { align: 'center' });
      
      // Support contact line
      doc?.setFontSize(8);
      doc?.text('If you have any questions or complaints about this transaction, please contact our support team at', 
                pageWidth / 2, skupadiY + 15, { align: 'center' });
      
      // Support email line with emphasis
      doc?.setFont('helvetica', 'bold');
      doc?.text('support@skupadi.com', pageWidth / 2, skupadiY + 22, { align: 'center' });

      // Skupadi branding - commented out
      // if (config?.showPoweredBy) {
      //   doc?.setFontSize(8);
      //   doc?.setFont('helvetica', 'normal');
      //   doc?.setTextColor(colors?.primary);
      //   doc?.text('Powered by Skupadi School Management System', pageWidth / 2, footerY + 15, { align: 'center' });
      // }

      // Watermark
      if (config?.invoiceElements?.watermark) {
        doc?.setTextColor(200, 200, 200);
        doc?.setFontSize(50);
        doc?.setFont('helvetica', 'bold');
        doc?.text('INVOICE', pageWidth / 2, pageHeight / 2, { 
          align: 'center',
          angle: 45
        });
      }

      return doc;
    } catch (error) {
      console.error('Error generating PDF:', error);
      throw new Error(`PDF generation failed: ${error?.message}`);
    }
  }

  /**
   * Generate and download single invoice PDF
   */
  async downloadInvoicePDF(invoiceData, filename = null) {
    try {
      const doc = await this.generateInvoicePDF(invoiceData);
      const pdfFilename = filename || `Invoice-${invoiceData?.id || 'Unknown'}.pdf`;
      doc?.save(pdfFilename);
      return { success: true, filename: pdfFilename };
    } catch (error) {
      console.error('Error downloading invoice PDF:', error);
      return { success: false, error: error?.message };
    }
  }

  /**
   * Generate bulk invoice PDFs
   */
  async generateBulkInvoicePDFs(invoicesData, options = {}) {
    try {
      const results = [];
      const errors = [];

      for (let i = 0; i < invoicesData?.length; i++) {
        const invoice = invoicesData?.[i];
        try {
          const doc = await this.generateInvoicePDF(invoice);
          const filename = `Invoice-${invoice?.id}.pdf`;
          
          if (options?.download !== false) {
            doc?.save(filename);
          }
          
          results?.push({
            invoiceId: invoice?.id,
            success: true,
            filename,
            pdfBlob: doc?.output('blob')
          });
        } catch (error) {
          errors?.push({
            invoiceId: invoice?.id,
            success: false,
            error: error?.message
          });
        }
      }

      return {
        success: errors?.length === 0,
        results,
        errors,
        totalProcessed: invoicesData?.length,
        successCount: results?.length,
        errorCount: errors?.length
      };
    } catch (error) {
      console.error('Error generating bulk PDFs:', error);
      return {
        success: false,
        error: error?.message,
        results: [],
        errors: []
      };
    }
  }

  /**
   * Preview invoice as data URL (for display in modal)
   */
  async previewInvoicePDF(invoiceData) {
    try {
      const doc = await this.generateInvoicePDF(invoiceData);
      return doc?.output('datauristring');
    } catch (error) {
      console.error('Error generating PDF preview:', error);
      throw error;
    }
  }

  /**
   * Generate comprehensive report summary PDF
   */
  async generateReportSummaryPDF(reportsData, options = {}) {
    try {
      const branding = this.getSchoolBranding();
      const config = this.getInvoiceConfig();
      const doc = new jsPDF(this.defaultConfig);

      // Page dimensions
      const pageWidth = doc?.internal?.pageSize?.getWidth();
      const pageHeight = doc?.internal?.pageSize?.getHeight();
      const margin = this.defaultConfig?.margins?.left;
      const contentWidth = pageWidth - (margin * 2);

      let yPosition = margin;

      // Color scheme
      const colors = {
        primary: '#081C48',
        secondary: '#3B82F6',
        accent: '#E3F2FD',
        success: '#22C55E',
        warning: '#F59E0B',
        danger: '#EF4444'
      };

      // Header Section
      doc?.setFillColor(8, 28, 72); // #081C48
      doc?.rect(0, 0, pageWidth, 40, 'F');

      // Title
      doc?.setTextColor(255, 255, 255);
      doc?.setFontSize(20);
      doc?.setFont('helvetica', 'bold');
      doc?.text(reportsData?.title || 'Reports Summary', pageWidth / 2, 20, { align: 'center' });
      
      doc?.setFontSize(12);
      doc?.setFont('helvetica', 'normal');
      doc?.text(branding?.schoolName || 'School Name', pageWidth / 2, 30, { align: 'center' });

      yPosition = 50;

      // Report Generation Info
      doc?.setTextColor(0, 0, 0);
      doc?.setFontSize(10);
      doc?.setFont('helvetica', 'normal');
      doc?.text(`Generated on: ${reportsData?.generatedDate}`, margin, yPosition);
      doc?.text(`Report Type: Complete Financial & Analytics Summary`, margin, yPosition + 5);

      yPosition += 20;

      // Financial Reports Section
      if (reportsData?.financialReports?.length > 0) {
        // Section header
        doc?.setFillColor(8, 28, 72);
        doc?.rect(margin, yPosition, contentWidth, 12, 'F');
        
        doc?.setTextColor(255, 255, 255);
        doc?.setFontSize(14);
        doc?.setFont('helvetica', 'bold');
        doc?.text('FINANCIAL REPORTS', margin + 5, yPosition + 8);

        yPosition += 20;

        // Financial reports table
        doc?.setTextColor(0, 0, 0);
        doc?.setFontSize(10);
        doc?.setFont('helvetica', 'bold');
        
        // Table headers
        doc?.text('Report Type', margin + 5, yPosition);
        doc?.text('Value', margin + 80, yPosition);
        doc?.text('Status', margin + 130, yPosition);
        doc?.text('Period', margin + 160, yPosition);
        
        // Header line
        doc?.setLineWidth(0.5);
        doc?.line(margin, yPosition + 2, margin + contentWidth, yPosition + 2);

        yPosition += 8;

        // Financial report items
        doc?.setFont('helvetica', 'normal');
        reportsData?.financialReports?.forEach((report, index) => {
          if (index % 2 === 1) {
            doc?.setFillColor(248, 249, 250);
            doc?.rect(margin, yPosition - 3, contentWidth, 10, 'F');
          }

          doc?.setTextColor(0, 0, 0);
          doc?.text(report?.reportType || 'N/A', margin + 5, yPosition);
          
          // Format value
          let value = 'N/A';
          if (typeof report?.amount !== 'undefined') {
            value = `₦${(report?.amount / 1000000)?.toFixed(1)}M`;
          } else if (typeof report?.percentage !== 'undefined') {
            value = `${report?.percentage}%`;
          }
          doc?.text(value, margin + 80, yPosition);
          
          // Status with color coding
          const status = report?.status || 'N/A';
          if (status === 'Generated' || status === 'On Track' || status === 'Healthy') {
            doc?.setTextColor(34, 197, 94); // Green
          } else if (status === 'Pending' || status === 'Warning') {
            doc?.setTextColor(245, 158, 11); // Yellow
          } else {
            doc?.setTextColor(0, 0, 0); // Default
          }
          doc?.text(status, margin + 130, yPosition);
          
          doc?.setTextColor(0, 0, 0);
          doc?.text(report?.period || 'Current Term', margin + 160, yPosition);
          
          yPosition += 10;
        });

        yPosition += 10;
      }

      // Analytics Reports Section
      if (reportsData?.analyticsReports?.length > 0) {
        // Check if we need a new page
        if (yPosition > pageHeight - 80) {
          doc?.addPage();
          yPosition = margin;
        }

        // Section header
        doc?.setFillColor(8, 28, 72);
        doc?.rect(margin, yPosition, contentWidth, 12, 'F');
        
        doc?.setTextColor(255, 255, 255);
        doc?.setFontSize(14);
        doc?.setFont('helvetica', 'bold');
        doc?.text('PAYMENT ANALYTICS', margin + 5, yPosition + 8);

        yPosition += 20;

        // Analytics table
        doc?.setTextColor(0, 0, 0);
        doc?.setFontSize(10);
        doc?.setFont('helvetica', 'bold');
        
        // Table headers
        doc?.text('Metric', margin + 5, yPosition);
        doc?.text('Value', margin + 80, yPosition);
        doc?.text('Trend', margin + 130, yPosition);
        doc?.text('Status', margin + 160, yPosition);
        
        // Header line
        doc?.setLineWidth(0.5);
        doc?.line(margin, yPosition + 2, margin + contentWidth, yPosition + 2);

        yPosition += 8;

        // Analytics items
        doc?.setFont('helvetica', 'normal');
        reportsData?.analyticsReports?.forEach((report, index) => {
          if (index % 2 === 1) {
            doc?.setFillColor(248, 249, 250);
            doc?.rect(margin, yPosition - 3, contentWidth, 10, 'F');
          }

          doc?.setTextColor(0, 0, 0);
          doc?.text(report?.metric || 'N/A', margin + 5, yPosition);
          
          // Format value
          let value = 'N/A';
          if (typeof report?.value === 'number') {
            if (report?.currency === 'NGN') {
              value = `₦${report?.value?.toLocaleString()}`;
            } else if (report?.metric?.includes('Rate') || report?.metric?.includes('Percentage')) {
              value = `${report?.value}%`;
            } else {
              value = report?.value?.toLocaleString();
            }
          }
          doc?.text(value, margin + 80, yPosition);
          
          // Trend with color coding
          let trend = '';
          if (report?.growth) {
            trend = `+${report?.growth}%`;
            doc?.setTextColor(34, 197, 94); // Green for positive growth
          } else if (report?.reduction) {
            trend = `${report?.reduction}%`;
            doc?.setTextColor(239, 68, 68); // Red for reduction
          } else if (report?.target) {
            trend = `Target: ${report?.target}%`;
            doc?.setTextColor(107, 114, 128); // Gray for targets
          } else {
            trend = 'Stable';
            doc?.setTextColor(107, 114, 128); // Gray for stable
          }
          doc?.text(trend, margin + 130, yPosition);
          
          // Status
          const status = report?.status || 'N/A';
          if (status?.includes('Above') || status?.includes('Increasing') || status?.includes('Improving')) {
            doc?.setTextColor(34, 197, 94); // Green
          } else if (status?.includes('Below') || status?.includes('Warning')) {
            doc?.setTextColor(245, 158, 11); // Yellow
          } else {
            doc?.setTextColor(0, 0, 0); // Default
          }
          doc?.text(status, margin + 160, yPosition);
          
          doc?.setTextColor(0, 0, 0);
          yPosition += 10;
        });

        yPosition += 10;
      }

      // Summary Statistics
      const totalFinancialReports = reportsData?.financialReports?.length || 0;
      const totalAnalyticsReports = reportsData?.analyticsReports?.length || 0;
      const totalReports = totalFinancialReports + totalAnalyticsReports;

      // Summary box
      doc?.setFillColor(227, 242, 253); // Light blue background
      doc?.rect(margin, yPosition, contentWidth, 25, 'F');

      doc?.setTextColor(8, 28, 72);
      doc?.setFontSize(12);
      doc?.setFont('helvetica', 'bold');
      doc?.text('SUMMARY STATISTICS', margin + 5, yPosition + 8);

      doc?.setFontSize(10);
      doc?.setFont('helvetica', 'normal');
      doc?.text(`Total Reports: ${totalReports}`, margin + 5, yPosition + 15);
      doc?.text(`Financial Reports: ${totalFinancialReports}`, margin + 5, yPosition + 20);
      doc?.text(`Analytics Reports: ${totalAnalyticsReports}`, margin + 80, yPosition + 20);

      // Footer
      const footerY = pageHeight - 35;
      
      // Skupadi + Astroidegita Technologies Branding Section
      doc?.setTextColor(8, 28, 72); // #081C48 color
      doc?.setFontSize(9);
      doc?.setFont('helvetica', 'normal');
      
      // Copyright line
      doc?.text('©2025 Skupadi a product of Astroidegita Technologies LTD (RC 8354011).', pageWidth / 2, footerY + 8, { align: 'center' });
      
      // Support contact lines
      doc?.setFontSize(8);
      doc?.text('If you have any questions or complaints about this report, please contact our support team at', 
                pageWidth / 2, footerY + 15, { align: 'center' });
      
      doc?.setFont('helvetica', 'bold');
      doc?.text('support@skupadi.com', pageWidth / 2, footerY + 22, { align: 'center' });

      // Download the PDF
      if (options?.download !== false) {
        const filename = `${options?.filename || 'Report_Summary'}.pdf`;
        doc?.save(filename);
      }

      return {
        success: true,
        filename: `${options?.filename || 'Report_Summary'}.pdf`,
        recordCount: totalReports
      };

    } catch (error) {
      console.error('Error generating report summary PDF:', error);
      return {
        success: false,
        error: error?.message
      };
    }
  }

  /**
   * Get PDF generation status and capabilities
   */
  getCapabilities() {
    return {
      formats: ['A4', 'Letter'],
      orientations: ['portrait', 'landscape'],
      templates: ['standard', 'modern', 'classic', 'minimalist', 'detailed', 'corporate'],
      colorSchemes: ['blue', 'green', 'purple', 'red', 'gray', 'orange'],
      features: {
        schoolBranding: true,
        qrCodes: true,
        watermarks: true,
        digitalSignature: true,
        bulkGeneration: true,
        customTemplates: true,
        reportSummaries: true,
        multiLanguage: false
      }
    };
  }
}

// Create and export singleton instance
const pdfGenerationService = new PDFGenerationService();
export default pdfGenerationService;